# Generated by Django 4.2.6 on 2023-10-18 02:14

from django.db import migrations

def load_initial_data(apps, schema_editor):
    ceo_model = apps.get_model('apple_ceos', 'CEO')
    ceo_model.objects.create (name = "Gil Amelio", slug = "gil_amelio", first_year_active = 1996)
    ceo_model.objects.create (name = "Mike Markkula", slug = "mike_markkula", first_year_active = 1977)
    ceo_model.objects.create (name = "Tim Cook", slug = "tim_cook", first_year_active = 2011)
    ceo_model.objects.create (name = "Mike Scott", slug = "mike_scott", first_year_active = 1978)
    ceo_model.objects.create (name = "John Sculley", slug = "john_sculley", first_year_active = 1983)
    ceo_model.objects.create (name = "Steve Jobs", slug = "steve_jobs", first_year_active = 1976)
    ceo_model.objects.create (name = "Steve Jobs", slug = "steve_jobs", first_year_active = 1997)

class Migration(migrations.Migration):

    dependencies = [
        ('apple_ceos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
